baseURL = 'https://strebeck.net/'
languageCode = 'en-us'
title = 'STREBECK'
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true

  [params.homeInfoParams]
    Title = "STREBECK"
    Content = "Cloud & DevOps Engineer"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jstrebeck"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jstrebeck"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:josh@strebeck.net"

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects"
  weight = 15

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 30
